//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDBCLI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDBCLI.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Database connection string. 的本地化字符串。
        /// </summary>
        internal static string AddDatabaseCommandConnectionStringOptionDescription {
            get {
                return ResourceManager.GetString("AddDatabaseCommandConnectionStringOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a database configuration. 的本地化字符串。
        /// </summary>
        internal static string AddDatabaseCommandDescription {
            get {
                return ResourceManager.GetString("AddDatabaseCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database name. 的本地化字符串。
        /// </summary>
        internal static string AddDatabaseCommandNameOptionDescription {
            get {
                return ResourceManager.GetString("AddDatabaseCommandNameOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database type. 的本地化字符串。
        /// </summary>
        internal static string AddDatabaseCommandTypeOptionDescription {
            get {
                return ResourceManager.GetString("AddDatabaseCommandTypeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage database configurations. 的本地化字符串。
        /// </summary>
        internal static string DatabaseCommandDescription {
            get {
                return ResourceManager.GetString("DatabaseCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete a database configuration. 的本地化字符串。
        /// </summary>
        internal static string DeleteDatabaseCommandDescription {
            get {
                return ResourceManager.GetString("DeleteDatabaseCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database name. 的本地化字符串。
        /// </summary>
        internal static string DeleteDatabaseCommandNameOptionDescription {
            get {
                return ResourceManager.GetString("DeleteDatabaseCommandNameOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute a SQL statement on a specified database. 的本地化字符串。
        /// </summary>
        internal static string ExecuteCommandDescription {
            get {
                return ResourceManager.GetString("ExecuteCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL file to execute. 的本地化字符串。
        /// </summary>
        internal static string ExecuteCommandFileOptionDescription {
            get {
                return ResourceManager.GetString("ExecuteCommandFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output csv file. 的本地化字符串。
        /// </summary>
        internal static string ExecuteCommandOutputOptionDescription {
            get {
                return ResourceManager.GetString("ExecuteCommandOutputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL statement to execute. 的本地化字符串。
        /// </summary>
        internal static string ExecuteCommandSQLOptionDescription {
            get {
                return ResourceManager.GetString("ExecuteCommandSQLOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database name to execute SQL on. 的本地化字符串。
        /// </summary>
        internal static string ExecuteCommnadDatabaseOptionDescription {
            get {
                return ResourceManager.GetString("ExecuteCommnadDatabaseOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List all configured databases. 的本地化字符串。
        /// </summary>
        internal static string ListDatabaseCommandDescription {
            get {
                return ResourceManager.GetString("ListDatabaseCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionString 的本地化字符串。
        /// </summary>
        internal static string ListDatabaseTableConnectionStringTitle {
            get {
                return ResourceManager.GetString("ListDatabaseTableConnectionStringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ListDatabaseTableNameTitle {
            get {
                return ResourceManager.GetString("ListDatabaseTableNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string ListDatabaseTableTypeTitle {
            get {
                return ResourceManager.GetString("ListDatabaseTableTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relational database command-line tool. 的本地化字符串。
        /// </summary>
        internal static string RDBCLICommandDescription {
            get {
                return ResourceManager.GetString("RDBCLICommandDescription", resourceCulture);
            }
        }
    }
}
